### ISSUE TITLE
프로젝트를 .exe 파일로 만들 때 경로문제

### ISSUE THREAD

**Issue by wjdwocks** [JongEonBaek/Requirements3#26]
내가 사용하는 환경에서의 Json파일이나 jpg파일의 경로가 .jar파일로 만들어서 빌드시켰을 때의 경로가 다른 현상이 발생함.
java.io.FileNotFoundException: C:\Users\user\Desktop\요구사항3\Requirements3\out\artifacts\Requirements3_jar\Tetris_game\src\Settings.json (지정된 경로를 찾을 수 없습니다)
이런 에러 메시지가 뜸.
경로들을 다 뜯어 고쳐야 할듯

**Comment by wjdwocks** [comment]
resource파일을 따로 만든 뒤 빌드 시에 리소스파일을 따로 첨가하여 .exe파일을 만드는 기능이 있었다.

**Comment by BJEon01** [comment]
경로 수정 후 정상작동 확인 함. 굳굳
